### ISSUE TITLE
Use `.bracket-matcher .region` to select highlighted brackets.

### ISSUE THREAD

**Issue by AnuragVyas14** [btleffler/lunarized-solo-syntax#2]
In index.less: Use `.bracket-matcher .region` to select highlighted brackets.

**Comment by btleffler** [comment]
@AnuragVyas14, the theme is using `.bracket-matcher` in [styles/base.less](https://github.com/btleffler/lunarized-solo-syntax/blob/master/styles/base.less#L45). Could you elaborate on how your suggestion would be better?

Thanks!
